# Generated by Django 5.1.2 on 2024-11-12 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turfowner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('expired', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('turfname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfowner.turf_table')),
            ],
        ),
        migrations.CreateModel(
            name='BookingSlotTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('slots', models.JSONField(null=True)),
                ('expired', models.BooleanField(default=False)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfowner.turf_table')),
            ],
            options={
                'unique_together': {('turf', 'booking_date')},
            },
        ),
    ]
