# Generated by Django 5.1.2 on 2024-11-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_bookingslottable_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingslottable',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
