# Generated by Django 5.1.2 on 2024-11-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_bookingslottable_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingslottable',
            name='booking_date',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
