# Generated by Django 5.1.2 on 2024-11-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_bookingslottable_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookingtable',
            name='slots',
            field=models.TextField(),
        ),
    ]
