# Generated by Django 5.1.2 on 2024-11-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_userbookingtable_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookingtable',
            name='slots',
            field=models.JSONField(default=list, null=True),
        ),
    ]
