# Generated by Django 5.1.2 on 2024-11-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_userbookingtable_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookingtable',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
