# Generated by Django 5.1.2 on 2024-11-12 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='turf_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='turfimages/img.png', upload_to='turfimages')),
                ('name', models.CharField(max_length=150)),
                ('game_type', models.CharField(max_length=50)),
                ('location', models.TextField()),
                ('location_url', models.TextField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('rent', models.CharField(default=0, max_length=5)),
                ('discription', models.TextField()),
                ('slots', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('ownername', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
