# Generated by Django 5.1.2 on 2024-11-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfowner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf_table',
            name='closed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='turf_table',
            name='slots',
            field=models.BooleanField(default=True),
        ),
    ]
