# Generated by Django 5.1.2 on 2024-09-12 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfowner', '0003_reviewtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewtable',
            name='turf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turfowner.turf_table'),
        ),
    ]
